```{r}
setwd("~/Documents/Terrapins/data")
library(car)
library(plot3D)
library(lattice)
terrapin.all<-read.csv("terrapin-all-r.csv")
terrapin.all
lm.terrapin<-lm(log(Max)~log(CL)+Headstart+log(CL)*Headstart, data=terrapin.all)
summary(lm.terrapin)
plot(lm.terrapin)
```
```{r}
xyplot(log(Max)~log(CL), groups=Headstart, col=c("red","blue"), type=c("p","r"), xlab="Log Carapace Length (mm)", ylab="Log Max Bite Force (N)", data=terrapin.all)
dev.print(pdf, "carapace-all.pdf")
##headstarts are red and wild are blue
```
```{r}
##range of individuals 86-117mm carapace length.  range determined by largest headstart (117mm) and smallest wild (86mm)
setwd("~/Documents/Terrapins/data")
cl.range<-read.csv("terrapin-cl(86-117).csv")
xyplot(log(Max)~log(CL), groups=Headstart, type=c("p","r"), xlab="Log Carapace Length (mm)", ylab="Log Max Bite Force (N)", col=c("blue","red"), data=cl.range)
dev.print(pdf, "carapace-range.pdf")
```
```{r}
##significance for above figure  
lm.terrapin.CL<-lm(log(Max)~log(CL)+Headstart+log(CL)*Headstart, data=cl.range)
summary(lm.terrapin.CL)
plot(lm.terrapin.CL)
Anova(lm.terrapin.CL, type=3)
```
```{r}
##same for HW
xyplot(log(Max)~log(HW), groups=Headstart, type=c("p","r"), xlab="Log Head Width (mm)", ylab="Log Max Bite Force (N)", col=c("blue", "red"), data=terrapin.all)
dev.print(pdf, "hw-all.pdf")
```
```{r}
setwd("~/Documents/Terrapins/data")
hw.range<-read.csv("terrapin-hw(16.5-23).csv")
xyplot(log(Max)~log(HW), groups=Headstart, type=c("p","r"), xlab="Log Head Width (mm)", ylab="Log Max Bite Force (N)", col=c("blue", "red"), data=hw.range)
dev.print(pdf, "hw-range.pdf")
```
```{r}
##significance for above figure  
lm.terrapin.HW<-lm(log(Max)~log(HW)+Headstart+log(HW)*Headstart, data=hw.range)
summary(lm.terrapin.HW)
plot(lm.terrapin.HW)
Anova(lm.terrapin.HW, type=3)
```

```{r}
##need to do step-wise regression to see if best indicators of bite force
step(lm(log(Max)~log(CL)+log(HW)+log(HH)+log(CW),data=terrapin.all),direction="backward")
best<-lm(log(Max) ~ log(CL) + log(HW), data=terrapin.all)
summary(best)
##add headstart 
```
```{r}
setwd("~/Documents/Terrapins/data")
biters<-read.csv("terrapin-biters.csv")
x <- hw <- log(biters$HW)
y <- cl <- log(biters$CL)
z <- max <- log(biters$Max)
scatter3D(x, y, z, phi = 20, theta=20, pch=1, bty ="g", xlab="Head Width (mm)", ylab="Carapace Length (mm)",zlab="Bite Force (N)")
```
```{r}
fit <- lm(z ~ x + y)
grid.lines = 26
x.pred <- seq(min(x), max(x), length.out = grid.lines)
y.pred <- seq(min(y), max(y), length.out = grid.lines)
xy <- expand.grid( x = x.pred, y = y.pred)
z.pred <- matrix(predict(fit, newdata = xy), 
                 nrow = grid.lines, ncol = grid.lines)
fitpoints <- predict(fit)
scatter3D(x, y, z, pch = 21, cex=1, 
    theta = 35, phi = 20, bty ="g",
    xlab = "Head Width (mm)",  ylab = "Carapace Length (mm)", zlab = "Bite Force (N)",  
    surf = list(x = x.pred, y = y.pred, z = z.pred,  
    facets = NA, fit = fitpoints))
dev.print(pdf, "surfaceplot.pdf")
```
```{r}
xyplot(log(CL)~log(HW), groups=Headstart, type=c("p","r"), xlab="Log Head Width (mm)", ylab="Log Carapace Length (mm)", col=c("blue", "red"), data=terrapin.all)
```
```{r}
lm.terrapin.HW.CL<-lm(log(CL)~log(HW)+Headstart+log(HW)*Headstart, data=terrapin.all)
summary(lm.terrapin.HW.CL)
plot(lm.terrapin.HW.CL)
Anova(lm.terrapin.HW.CL, type=3)
```
```{r}
xyplot(log(CL)~log(HW), groups=Headstart, type=c("p","r"), xlab="Log Head Width (mm)", ylab="Log Carapace Length (mm)", col=c("blue", "red"), data=cl.range)
```
```{r}
lm.HW.CL<-lm(log(CL)~log(HW)+Headstart+log(HW)*Headstart, data=cl.range)
summary(lm.HW.CL)
plot(lm.HW.CL)
Anova(lm.HW.CL, type=3)
```




